name: "Deploy app to github pages"

on:
  push:
    branches: [github-pages]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: use node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: build
        run: |
          npm i
          npm run build
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
